// <auto-generated />
using System;
using DataAccesLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccesLayer.Migrations
{
    [DbContext(typeof(SolutionContext))]
    partial class SolutionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccesLayer.Models.CriterioPremios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cantGanadores")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("criterioPremios");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Eventos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Torneosid")
                        .HasColumnType("int");

                    b.Property<string>("equipo1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipo2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("golesEquipo1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("golesEquipo2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_Torneo")
                        .HasColumnType("int");

                    b.Property<string>("resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("torneoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Torneosid");

                    b.HasIndex("torneoid");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("DataAccesLayer.Models.PencaCompartidas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("criterioPremiosid")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("torneoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("criterioPremiosid");

                    b.HasIndex("torneoid");

                    b.ToTable("PencasCompartidas");
                });

            modelBuilder.Entity("DataAccesLayer.Models.PencaEmpresariales", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("torneoid")
                        .HasColumnType("int");

                    b.Property<string>("usuarioCreadorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("torneoid");

                    b.HasIndex("usuarioCreadorId");

                    b.ToTable("PencasEmpresariales");
                });

            modelBuilder.Entity("DataAccesLayer.Models.PencaUsuario_Compartidas", b =>
                {
                    b.Property<string>("id_Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("id_Penca")
                        .HasColumnType("int");

                    b.HasKey("id_Usuario", "id_Penca");

                    b.HasIndex("id_Penca");

                    b.ToTable("pencaUsuarioCompartida");
                });

            modelBuilder.Entity("DataAccesLayer.Models.PencaUsuario_Empresariales", b =>
                {
                    b.Property<string>("id_Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("id_Penca")
                        .HasColumnType("int");

                    b.HasKey("id_Usuario", "id_Penca");

                    b.HasIndex("id_Penca");

                    b.ToTable("pencaUsuarioEmpresarial");
                });

            modelBuilder.Entity("DataAccesLayer.Models.PorcentajesPremios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("criterioid")
                        .HasColumnType("int");

                    b.Property<int>("id_CriterioPremio")
                        .HasColumnType("int");

                    b.Property<int>("porcentaje")
                        .HasColumnType("int");

                    b.Property<int>("posicion")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("criterioid");

                    b.ToTable("porcentajePremios");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Premios", b =>
                {
                    b.Property<string>("id_Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("id_Penca")
                        .HasColumnType("int");

                    b.Property<int>("criterioPremiosid")
                        .HasColumnType("int");

                    b.Property<int>("id_CriterioPremio")
                        .HasColumnType("int");

                    b.Property<bool>("pago")
                        .HasColumnType("bit");

                    b.Property<float>("valorPremio")
                        .HasColumnType("real");

                    b.HasKey("id_Usuario", "id_Penca");

                    b.HasIndex("criterioPremiosid");

                    b.HasIndex("id_Penca");

                    b.ToTable("Premios");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Subscripciones", b =>
                {
                    b.Property<string>("id_Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("id_Penca")
                        .HasColumnType("int");

                    b.Property<string>("nroTar_Credito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Usuario", "id_Penca");

                    b.HasIndex("id_Penca");

                    b.ToTable("Subscripciones");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Torneos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("fechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataAccesLayer.Models.Eventos", b =>
                {
                    b.HasOne("DataAccesLayer.Models.Torneos", null)
                        .WithMany("eventos")
                        .HasForeignKey("Torneosid");

                    b.HasOne("DataAccesLayer.Models.Torneos", "torneo")
                        .WithMany()
                        .HasForeignKey("torneoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("torneo");
                });

            modelBuilder.Entity("DataAccesLayer.Models.PencaCompartidas", b =>
                {
                    b.HasOne("DataAccesLayer.Models.CriterioPremios", "criterioPremios")
                        .WithMany()
                        .HasForeignKey("criterioPremiosid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccesLayer.Models.Torneos", "torneo")
                        .WithMany("pencasCompartidas")
                        .HasForeignKey("torneoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("criterioPremios");

                    b.Navigation("torneo");
                });

            modelBuilder.Entity("DataAccesLayer.Models.PencaEmpresariales", b =>
                {
                    b.HasOne("DataAccesLayer.Models.Torneos", "torneo")
                        .WithMany("pencasEmpresariales")
                        .HasForeignKey("torneoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccesLayer.Models.Users", "usuarioCreador")
                        .WithMany()
                        .HasForeignKey("usuarioCreadorId");

                    b.Navigation("torneo");

                    b.Navigation("usuarioCreador");
                });

            modelBuilder.Entity("DataAccesLayer.Models.PencaUsuario_Compartidas", b =>
                {
                    b.HasOne("DataAccesLayer.Models.PencaCompartidas", "pencaCompartida")
                        .WithMany("pencaUsuarioCompartida")
                        .HasForeignKey("id_Penca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccesLayer.Models.Users", "usuario")
                        .WithMany("pencaUsuarioCompartida")
                        .HasForeignKey("id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("pencaCompartida");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("DataAccesLayer.Models.PencaUsuario_Empresariales", b =>
                {
                    b.HasOne("DataAccesLayer.Models.PencaEmpresariales", "pencaEmpresarial")
                        .WithMany("pencaUsuarioEmpresarial")
                        .HasForeignKey("id_Penca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccesLayer.Models.Users", "usuario")
                        .WithMany("pencaUsuarioEmpresarial")
                        .HasForeignKey("id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("pencaEmpresarial");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("DataAccesLayer.Models.PorcentajesPremios", b =>
                {
                    b.HasOne("DataAccesLayer.Models.CriterioPremios", "criterio")
                        .WithMany()
                        .HasForeignKey("criterioid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("criterio");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Premios", b =>
                {
                    b.HasOne("DataAccesLayer.Models.CriterioPremios", "criterioPremios")
                        .WithMany()
                        .HasForeignKey("criterioPremiosid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccesLayer.Models.PencaCompartidas", "pencaCompartida")
                        .WithMany("premios")
                        .HasForeignKey("id_Penca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccesLayer.Models.Users", "usuario")
                        .WithMany("Premios")
                        .HasForeignKey("id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("criterioPremios");

                    b.Navigation("pencaCompartida");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Subscripciones", b =>
                {
                    b.HasOne("DataAccesLayer.Models.PencaEmpresariales", "pencaEmpresarial")
                        .WithMany("Subscripciones")
                        .HasForeignKey("id_Penca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccesLayer.Models.Users", "usuario")
                        .WithMany("Subscripciones")
                        .HasForeignKey("id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pencaEmpresarial");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccesLayer.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccesLayer.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccesLayer.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccesLayer.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccesLayer.Models.PencaCompartidas", b =>
                {
                    b.Navigation("pencaUsuarioCompartida");

                    b.Navigation("premios");
                });

            modelBuilder.Entity("DataAccesLayer.Models.PencaEmpresariales", b =>
                {
                    b.Navigation("Subscripciones");

                    b.Navigation("pencaUsuarioEmpresarial");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Torneos", b =>
                {
                    b.Navigation("eventos");

                    b.Navigation("pencasCompartidas");

                    b.Navigation("pencasEmpresariales");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Users", b =>
                {
                    b.Navigation("Premios");

                    b.Navigation("Subscripciones");

                    b.Navigation("pencaUsuarioCompartida");

                    b.Navigation("pencaUsuarioEmpresarial");
                });
#pragma warning restore 612, 618
        }
    }
}
